#!/bin/bash
# Manual GCP deployment using gcloud REST API or web console

echo "🚀 GCP Cloud Run Deployment Instructions"
echo ""
echo "Since gcloud CLI has a path issue, you have 2 options:"
echo ""
echo "Option 1: Use GCP Console (Easiest - 5 minutes)"
echo "=========================================="
echo "1. Go to: https://console.cloud.google.com/run/create?project=ad-tech-analyzer"
echo "2. Click 'CREATE SERVICE'"
echo "3. Select: 'Continuously deploy from a repository'"
echo "4. Click 'SET UP WITH CLOUD BUILD'"
echo "5. Connect GitHub repo: joshidikshant/ad-tech-analyzer"
echo "6. Branch: main"
echo "7. Build Type: Dockerfile"
echo "8. Dockerfile path: /Dockerfile"
echo "9. Service name: ad-tech-analyzer"
echo "10. Region: us-central1"
echo "11. CPU: 1, Memory: 2 GiB"
echo "12. Request timeout: 300"
echo "13. Maximum instances: 10"
echo "14. Ingress: Allow all traffic"
echo "15. Authentication: Allow unauthenticated"
echo "16. Container port: 3001"
echo "17. Click 'CREATE'"
echo ""
echo "Option 2: Fix gcloud and use CLI"
echo "================================="
echo "Run these commands:"
echo "  rm -rf ~/google-cloud-sdk"
echo "  curl https://sdk.cloud.google.com | bash"
echo "  exec -l \$SHELL"
echo "  gcloud init"
echo "  cd /Users/Dikshant/Desktop/Projects/ad-tech-analyzer"
echo "  ./deploy-to-gcp.sh"
echo ""
