// Type definitions for Prebid.js data collection
// Generated by Gemini, refined for ad-tech-analyzer

/**
 * Represents the user IDs obtained from Prebid.js, typically from an ID module.
 */
export interface UserIds {
  tdid?: string; // TradeDesk ID
  pubcid?: string; // PubCommon ID
  uid2?: string; // Unified ID 2.0
  id5id?: string; // ID5
  criteoId?: string; // Criteo ID
  netId?: string; // LiveRamp IDL
  [key: string]: string | undefined;
}

/**
 * Represents a single bid response from a bidder.
 */
export interface BidResponse {
  bidderCode: string;
  width: number;
  height: number;
  adId: string;
  cpm: number;
  currency: string;
  originalCpm: number;
  originalCurrency: string;
  responseTimestamp: number;
  requestTimestamp: number;
  timeToRespond: number;
  statusMessage: string;
  creativeId?: string;
  dealId?: string;
  userId?: UserIds;
  userIdAsEids?: Array<{ source: string; uids: Array<{ id: string; ext?: object }> }>;
  meta?: {
    advertiserDomains?: string[];
    networkId?: number;
    demandSource?: string;
  };
}

/**
 * Represents an ad unit as configured in Prebid.js.
 */
export interface AdUnit {
  code: string;
  mediaTypes: {
    banner?: {
      sizes: number[][];
    };
    video?: {
      playerSize: number[][];
      context: 'instream' | 'outstream';
    };
    native?: object;
  };
  bids: Array<{ bidder: string; params: object }>;
}

/**
 * Represents the configuration object from Prebid.js.
 */
export interface Config {
  debug?: boolean;
  bidderTimeout?: number;
  enableSendAllBids?: boolean;
  priceGranularity?: string | object;
  userSync?: object;
  s2sConfig?: object;
  consentManagement?: object;
  uspConsent?: object;
  coppa?: boolean;
  deviceAccess?: boolean;
  schain?: object;
}

/**
 * The main interface for collected Prebid.js data.
 */
export interface PrebidData {
  config: Config;
  adUnits: AdUnit[];
  bidResponses: BidResponse[];
  version: string;
}

/**
 * Extracts relevant Prebid.js data from the window.pbjs object.
 *
 * @returns {PrebidData | null} The collected Prebid data, or null if pbjs is not available.
 */
export function extractPrebidData(): PrebidData | null {
  if (typeof window === 'undefined' || !window.pbjs) {
    console.warn('[Prebid Collector] window.pbjs not found. Cannot extract Prebid data.');
    return null;
  }

  const pbjs = window.pbjs;
  const prebidData: Partial<PrebidData> = {};

  try {
    // Get configuration
    if (typeof pbjs.getConfig === 'function') {
      const config = pbjs.getConfig();
      if (config) {
        prebidData.config = config as Config;
      }
    } else {
      console.warn('[Prebid Collector] pbjs.getConfig() not found.');
      prebidData.config = {};
    }
  } catch (error) {
    console.error('[Prebid Collector] Error getting configuration:', error);
    prebidData.config = {};
  }

  try {
    // Get ad units
    if (typeof pbjs.adUnits === 'object' && Array.isArray(pbjs.adUnits)) {
      prebidData.adUnits = pbjs.adUnits as AdUnit[];
    } else {
      console.warn('[Prebid Collector] pbjs.adUnits not found or not an array.');
      prebidData.adUnits = [];
    }
  } catch (error) {
    console.error('[Prebid Collector] Error getting ad units:', error);
    prebidData.adUnits = [];
  }

  try {
    // Get bid responses
    if (typeof pbjs.getAllAdUnits === 'function') {
      const allAdUnits = pbjs.getAllAdUnits();
      const bidResponses: BidResponse[] = [];
      allAdUnits.forEach((unit: any) => {
        if (unit.bids && Array.isArray(unit.bids)) {
          unit.bids.forEach((bid: any) => {
            if (bid.status === 'rendered' || bid.status === 'targetingSet') {
              bidResponses.push(bid as BidResponse);
            }
          });
        }
      });
      prebidData.bidResponses = bidResponses;
    } else {
      console.warn('[Prebid Collector] pbjs.getAllAdUnits() not found.');
      prebidData.bidResponses = [];
    }
  } catch (error) {
    console.error('[Prebid Collector] Error getting bid responses:', error);
    prebidData.bidResponses = [];
  }

  try {
    // Get Prebid.js version
    if (typeof pbjs.version === 'string') {
      prebidData.version = pbjs.version;
    } else {
      console.warn('[Prebid Collector] pbjs.version not found.');
      prebidData.version = 'unknown';
    }
  } catch (error) {
    console.error('[Prebid Collector] Error getting version:', error);
    prebidData.version = 'unknown';
  }

  return {
    config: prebidData.config || {},
    adUnits: prebidData.adUnits || [],
    bidResponses: prebidData.bidResponses || [],
    version: prebidData.version || 'unknown',
  } as PrebidData;
}

// Augment the Window interface to include pbjs
declare global {
  interface Window {
    pbjs?: {
      que?: any[];
      installed?: boolean;
      getConfig?: () => object;
      adUnits?: object[];
      getAllAdUnits?: () => object[];
      version?: string;
      [key: string]: any;
    };
  }
}
