#!/bin/bash

echo "🆓 Deploy EVERYTHING to Render.com (100% FREE)"
echo "=============================================="
echo ""
echo "✅ What we'll deploy:"
echo "   1. Backend (Web Service) - FREE"
echo "   2. Frontend (Static Site) - FREE"
echo "   3. All on one platform!"
echo ""
echo "📋 Prerequisites:"
echo "   - GitHub account"
echo "   - Code pushed to GitHub"
echo ""
read -p "Have you pushed to GitHub? (y/n): " PUSHED

if [ "$PUSHED" != "y" ]; then
    echo ""
    echo "❌ Please push to GitHub first:"
    echo ""
    echo "   cd /Users/Dikshant/Desktop/Projects/ad-tech-analyzer"
    echo "   git init"
    echo "   git add ."
    echo "   git commit -m 'Initial commit'"
    echo "   git branch -M main"
    echo "   git remote add origin https://github.com/YOUR-USERNAME/ad-tech-analyzer.git"
    echo "   git push -u origin main"
    echo ""
    exit 1
fi

echo ""
echo "Great! Let's deploy to Render.com"
echo ""
echo "================================================"
echo "STEP 1: Deploy Backend (Web Service)"
echo "================================================"
echo ""
echo "1. Go to https://render.com and sign up/login"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo ""
echo "4. Configure the backend:"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Name:          ad-tech-analyzer-api         │"
echo "   │ Region:        Oregon (or closest to you)   │"
echo "   │ Branch:        main                         │"
echo "   │ Root Directory: (leave empty)               │"
echo "   │ Runtime:       Node                         │"
echo "   │ Build Command: (leave empty)                │"
echo "   │ Start Command: npx tsx dashboard/api-server-mcp-final.ts │"
echo "   │ Instance Type: Free                         │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "5. Add Environment Variable:"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Key:   PORT                                 │"
echo "   │ Value: 3001                                 │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "6. Click 'Create Web Service'"
echo "7. Wait 5-10 minutes for deploy to complete"
echo ""
read -p "Press Enter when backend is deployed..."

echo ""
read -p "Enter your backend URL (e.g., https://ad-tech-analyzer-api.onrender.com): " BACKEND_URL

# Test backend
echo ""
echo "🧪 Testing backend..."
HEALTH_CHECK=$(curl -s "$BACKEND_URL/health" 2>&1)
if [[ $HEALTH_CHECK == *"ok"* ]]; then
    echo "✅ Backend health check passed!"
else
    echo "⚠️  Backend might still be deploying. Continue anyway..."
fi

echo ""
echo "================================================"
echo "STEP 2: Deploy Frontend (Static Site)"
echo "================================================"
echo ""
echo "1. In Render dashboard, click 'New +' → 'Static Site'"
echo "2. Connect the SAME GitHub repository"
echo ""
echo "3. Configure the frontend:"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Name:           ad-tech-analyzer-dashboard  │"
echo "   │ Branch:         main                        │"
echo "   │ Root Directory: dashboard                   │"
echo "   │ Build Command:  npm install && npm run build│"
echo "   │ Publish Dir:    dist                        │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "4. Add Environment Variable:"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Key:   VITE_API_URL                         │"
echo "   │ Value: $BACKEND_URL                         │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "5. Click 'Create Static Site'"
echo "6. Wait 3-5 minutes for build & deploy"
echo ""
read -p "Press Enter when frontend is deployed..."

echo ""
read -p "Enter your frontend URL (e.g., https://ad-tech-analyzer-dashboard.onrender.com): " FRONTEND_URL

echo ""
echo "================================================"
echo "STEP 3: Update Backend CORS"
echo "================================================"
echo ""
echo "We need to allow the frontend domain in backend CORS settings."
echo ""
echo "The backend CORS is already configured to accept *.onrender.com domains,"
echo "so you should be good to go!"
echo ""
echo "If you get CORS errors, the pattern /\\.onrender\\.com$/ in"
echo "dashboard/api-server-mcp-final.ts should allow it."
echo ""

echo ""
echo "================================================"
echo "STEP 4: Keep Backend Awake (Optional)"
echo "================================================"
echo ""
echo "Since Render free tier sleeps after 15 minutes of inactivity,"
echo "you can keep it awake using UptimeRobot (also free):"
echo ""
echo "1. Go to https://uptimerobot.com"
echo "2. Sign up (free, no credit card)"
echo "3. Add New Monitor:"
echo "   - Type: HTTP(s)"
echo "   - URL: $BACKEND_URL/health"
echo "   - Interval: 5 minutes"
echo ""
echo "This pings your backend every 5 minutes to keep it awake."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "✅ Deployment Complete!"
echo "================================================"
echo ""
echo "🎉 Your app is live at 100% FREE on Render.com!"
echo ""
echo "📊 Frontend: $FRONTEND_URL"
echo "🔌 Backend:  $BACKEND_URL"
echo ""
echo "🧪 Test your deployment:"
echo "   1. Open: $FRONTEND_URL"
echo "   2. Click 'Load Sample' button"
echo "   3. Or enter a URL and click 'Analyze'"
echo ""
echo "📊 Monitor your apps:"
echo "   https://dashboard.render.com"
echo ""
echo "💡 Tips:"
echo "   - Both services auto-deploy when you push to GitHub"
echo "   - Backend sleeps after 15 min (30-60s wake time)"
echo "   - Use UptimeRobot to keep backend awake"
echo "   - Free tier: 100GB bandwidth, 500 build minutes/month"
echo ""
echo "🎯 Everything on one platform - no Vercel needed!"
echo ""
echo "================================================"
echo ""
